### ISSUE TITLE
Support for cheats?

### ISSUE THREAD

**Issue by eisnerguy1** [jorio/Bugdom#2]
So, I was looking at the official [Bugdom Cheat Page](https://pangeasoft.net/bug/cheats.html), and I can't figure out how to activate some of these in 1.3.0:

• When you're on the Main Menu, hold down the F10 key and click the start game icon. This will bring up the Level Cheat Dialog which lets you start on any level.

• During game play, the following cheats work:
Apple + F1 = win this level
Apple + F2 = win the game
Apple + F3 = Full Health
Apple + F4 = Full Ball Timer
Apple + F5 = Full Inventory
Apple + F6 = Toggle Liquid Invincibility
Apple + F8 = frame rate
Apple + F9 = display debug

The only one I can get working is the Level Cheat Dialog.  I tried Command+FKey but, that didn't work.  I also tried Command+FN+FKey but, that didn't do anything either.  

Are these supported in 1.3.0?

Thanks!

**Comment by jorio** [comment]
Most of these still work, but you need to hold down the tilde key instead of command. I had to make this change because many Cmd+FKey shortcuts are reserved by macOS nowadays.

**Comment by eisnerguy1** [comment]
Ah, gotcha.  Thanks for clarifying that.

`+FN+F2 just produces this, instead of winning the game:
<img width="640" alt="Screen Shot 2021-01-02 at 10 34 30 AM" src="https://user-images.githubusercontent.com/3295271/103460660-23199400-4ce6-11eb-8063-8c1584e3ea5e.png">

`+FN+F8 doesn't display the frame rate

All of the other ones work.

Kinda related: I'm trying to get F12 to take screenshots.  According to the Instructions PDF:
F12: Does a special pause for taking screen shots. Input Sprocket is disabled during this special pause and there is no “paused” icon.

I've tried `+FN+F12, FN+F12 & ALT+FN+F12 and I'm not seeing any screenshots either on my Desktop or in ~/Library/Preferences/Bugdom.  Is this functionality still included?  Thanks!

**Comment by jorio** [comment]
Yeah, not all cheats are the same as the original game.

- \`+F2: indeed doesn't win the game anymore. Instead, it shows the player's coordinates now. (To win the game you could warp to Level 10 and hit `+F1.)

- \`+F8 (frame rate): I removed it because debug builds already show the framerate in the title bar. I could reintroduce that feature for release builds.

- \`+F12 (freeze frame): that feature wasn't in the copy of the source that Pangea sent me, but I could reintroduce it if you want.

Extra stuff I added:

- During the Pangea logo, hold down F1 and press Space to bring up a model viewer that I made to debug Quesa rendering issues. If you run this in windowed mode, information about the current model will be shown in the title bar. It's a bit clunky, but here are the controls:
    - [Tab] next model ([Shift-tab] previous model)
    - [Enter] next animation or object ([Shift-enter] previous anim or object),
    - [Space] toggle between skeletons and "display group" objects
    - [</>] swivel cam,
    - [z/shift-z] zoom in/out.

- During the Pangea logo, hold down F2 and press Space to show the Save screen, then the Load screen.

- During the Pangea logo, hold down F3 and press Space to show the Lose screen, then the Win screen.

- During the Pangea logo, hold down F4 and press Space to show the Settings screen.

- During the Pangea logo, hold down a number key (1 ... 0) and press Space to jump to the corresponding level

- In game, hit F11 to toggle between fullscreen/windowed mode (there might be issues with mouse capturing on macOS if you do that for now, but pausing then unpausing the game should fix it)

**Comment by eisnerguy1** [comment]
Thanks for clarifying that!  Having such a blast playing Bugdom again :D

**Comment by jorio** [comment]
Closing this issue because I documented the cheats in [CHEATS.md](https://github.com/jorio/Bugdom/blob/master/CHEATS.md) and added a link in the readme.
