### ISSUE TITLE
BUGDOM ALERT: No message system available?

### ISSUE THREAD

**Issue by jpenguin** [jorio/Bugdom#7]
When holding F10 and starting a new game on OpenSUSE Tumbleweed.

My build https://filedn.com/lHGef0SOQKnBTotcJeEfshJ/Games/Bugdom/Bugdom.tar.gz

**Comment by jorio** [comment]
The level cheat dialog brought up by F10 uses SDL_ShowMessageBox. The dialog has 11 buttons, which works fine on macOS and Windows, but not on Linux because [SDL's X11 dialogs cap out at 8 buttons](https://github.com/libsdl-org/SDL/blob/main/src/video/x11/SDL_x11messagebox.c#L45). I agree that this error message is a bit cryptic, so on Linux, we should implement this cheat in some other way.

You can still skip to any level without that dialog: hold down a number key and press space during the Pangea splash screen. For example, hold down '9' then press space to jump to level 9. [Other cheats here.](https://github.com/jorio/Bugdom/issues/2#issuecomment-753493273)

**Comment by jpenguin** [comment]
Thanks.  Bugdom was a big part of my childhood and I'm glad I can play it again, and I always skipped level 8 back then.
