### ISSUE TITLE
 my Linux binary?

### ISSUE THREAD

**Issue by jpenguin** [jorio/Bugdom#8]
Static, patched SDL for level select dialog.  Could you upload it as a release?

https://filedn.com/lHGef0SOQKnBTotcJeEfshJ/Games/Bugdom/Bugdom_linux64_1.3.0r1.tar.xz

**Comment by mittler-works** [comment]
I don't know how @jorio handles this, but I would never add a third party compiled binary as a release to my github project. That's nothing against you @jpenguin and I think the idea of releasing a Linux binary is very good.
Perhaps instead of a ready-made binary you can describe the way in which you have statically linked the libraries or even make a merge request with extended makefiles that offers an option to compile with static linked libraries, for example.

**Comment by jpenguin** [comment]
I cmompiled SDL with https://github.com/libsdl-org/SDL/blob/main/src/video/x11/SDL_x11messagebox.c#L45 changed to 11 (bugdom will run with stock SDL, this enables the F10 cheat).  Since I haven't figured out appimages yet, I just ran mkblob on the binary

mkblob /home/tuxpeng/Bugdom/build-release/Bugdom -o Bugdom.static -static

**Comment by jorio** [comment]
@mittler-works summed it up well -- As a matter of principle I don't feel comfortable releasing a binary that I haven't built myself because I can't audit how it was made.

That said, I do appreciate the work that you put into making the build. I took note of the interest for a Linux binary for future releases. Also, I intend to rework the level cheat dialog so it will work with an unmodified SDL on Linux.

Another way to make it easier for Linux users to play the game could be to have your favorite distro accept it into their package repository? For instance, there's a [PKGBUILD](https://aur.archlinux.org/packages/bugdom) for Arch Linux.

**Comment by jpenguin** [comment]
Understood

I just got it on Lutris
https://lutris.net/games/budom/

I'm trying to understand OpenSUSE OBS, so an appimage is possible
